### ISSUE TITLE
warning case-sensitive paths on a case-insensitive filesystem

### ISSUE THREAD

**Issue by l-we** [P1sec/pycrate#43] opened 2019-04-23 01:31 UTC
'pycrate_asn1dir/X509_2016.json'
  'pycrate_asn1dir/x509_2016.json'
  'pycrate_asn1dir/X509_2016.py'
  'pycrate_asn1dir/x509_2016.py'

**Comment by p1-bmu** [comment] 2019-04-23 06:51
Thanks for pointing this out: x509 has just been removed (was a duplicate of X509).

**Closed by p1-bmu** 2019-04-23 06:51 UTC
